import type { AppearanceSnapshot, ThemePreference } from "../../appearance/contract";
import { resolveSystemTheme } from "../../appearance/resolveTheme";
import type { DesktopBridge } from "../../bridge";
import type {
  CatalogPage,
  ConversationDisplayPage,
  RunAttachment,
  RunContext,
  SessionSummary,
  TranscriptPage,
  VerificationSummary,
  WorkspaceSummary,
} from "../../types";

const workspace: WorkspaceSummary = {
  id: "catalog-workspace",
  displayName: "sigil",
  serverVersion: "catalog",
  state: "ready",
};

const session: SessionSummary = {
  id: "catalog-session-complete",
  label: "Review parser recovery and verification",
  runCount: 4,
  foregroundRunId: "catalog-run-active",
};

const catalog: CatalogPage = {
  workspaceId: workspace.id,
  generation: 1,
  reconciledAtUnixMs: 1_784_419_200_000,
  degradedSourceCount: 0,
  identityConflictCount: 0,
  truncatedSourceCount: 0,
  entries: [
    {
      sessionRef: "catalog-session-complete.jsonl",
      sessionId: session.id,
      sourceState: "ready",
      sourceBytes: 1024,
      sourceModifiedAtUnixMs: 1_784_419_180_000,
      providerName: "deepseek",
      modelName: "deepseek-v4-flash",
      title: session.label,
      userMessageCount: 3,
      assistantMessageCount: 3,
      toolResultCount: 2,
      pinned: true,
    },
  ],
};

const transcript: TranscriptPage = {
  totalMessages: 4,
  messages: [
    {
      ordinal: 0,
      messageId: "catalog-user-1",
      role: "user",
      content: "检查 parser recovery。\n保留中文、emoji 🧭 与多行输入。",
      imageAttachmentCount: 0,
      truncated: false,
      originalContentBytes: 72,
    },
    {
      ordinal: 1,
      messageId: "catalog-assistant-1",
      role: "assistant",
      assistantKind: "final_answer",
      content: "### Current finding\n\nThe parser recovers safely, but the focused verification still fails.",
      imageAttachmentCount: 0,
      truncated: false,
      originalContentBytes: 93,
    },
    {
      ordinal: 2,
      messageId: "catalog-tool-1",
      role: "tool",
      toolName: "read_file",
      content: "Read src/parser.rs (184 lines)",
      imageAttachmentCount: 0,
      truncated: false,
      originalContentBytes: 31,
    },
    {
      ordinal: 3,
      messageId: "catalog-assistant-2",
      role: "assistant",
      assistantKind: "progress",
      content: "Running the exact parser check against the current workspace snapshot.",
      imageAttachmentCount: 0,
      truncated: false,
      originalContentBytes: 71,
    },
  ],
};

const displayPage: ConversationDisplayPage = {
  schemaVersion: 1,
  requestScope: "catalog-request-scope",
  throughSessionStreamSequence: "3",
  totalItems: "3",
  items: [
    {
      schemaVersion: 1,
      displayId: "catalog-durable-user",
      displayOrder: { sessionStreamSequence: "1", subindex: 0 },
      sourceEventId: "catalog-event-user",
      kind: "user_message",
      source: "durable_transcript",
      runId: "catalog-run-saved",
      status: "recorded",
      content: {
        type: "message",
        role: "user",
        text: "How do you understand this repository?",
        imageAttachmentCount: 0,
        truncated: false,
        originalContentBytes: 38,
      },
    },
    {
      schemaVersion: 1,
      displayId: "catalog-durable-assistant",
      displayOrder: { sessionStreamSequence: "2", subindex: 0 },
      sourceEventId: "catalog-event-assistant",
      kind: "assistant_message",
      source: "durable_transcript",
      runId: "catalog-run-saved",
      status: "succeeded",
      content: {
        type: "message",
        role: "assistant",
        assistantPhase: "final_answer",
        text: "## Repository capabilities\n\n- Read and search source files\n- Inspect directory structure\n- Modify code through audited tools\n- Run focused verification commands\n- Preserve an append-only conversation history",
        imageAttachmentCount: 0,
        truncated: false,
        originalContentBytes: 186,
      },
    },
    {
      schemaVersion: 1,
      displayId: "catalog-durable-reasoning",
      displayOrder: { sessionStreamSequence: "3", subindex: 0 },
      sourceEventId: "catalog-event-reasoning",
      kind: "reasoning",
      source: "durable_transcript",
      runId: "catalog-run-saved",
      status: "recorded",
      content: {
        type: "reasoning",
        text: "Inspecting the repository structure and relevant contracts.",
        truncated: false,
        originalContentBytes: 59,
      },
    },
  ],
  hasMore: false,
  gapFacts: [],
};

const attachment: RunAttachment = {
  run: {
    id: "catalog-run-active",
    sessionId: session.id,
    status: "running",
    permissionMode: "manual",
    reasoningEffort: "max",
    streamSequence: 10,
  },
  events: [
    {
      workspaceId: workspace.id,
      sessionId: session.id,
      runId: "catalog-run-active",
      sequence: 1, runSequence: "1",
      provisionalId: "catalog-live-user",
      replayable: true,
      kind: "run_started",
      text: "Repair the parser and rerun its focused verification.",
    },
    {
      workspaceId: workspace.id,
      sessionId: session.id,
      runId: "catalog-run-active",
      sequence: 2, runSequence: "2",
      provisionalId: "catalog-live-tool",
      replayable: true,
      kind: "tool_completed",
      itemId: "catalog-check",
      toolName: "shell",
      status: "failed",
      text: "parser::recovery_keeps_diagnostic_context failed",
    },
    {
      workspaceId: workspace.id,
      sessionId: session.id,
      runId: "catalog-run-active",
      sequence: 3, runSequence: "3",
      replayable: true,
      kind: "assistant_delta",
      text: "I found the failing assertion and am preparing a bounded fix.",
    },
    ...Array.from({ length: 6 }, (_, index) => ({
      workspaceId: workspace.id,
      sessionId: session.id,
      runId: "catalog-run-active",
      sequence: index + 4,
      runSequence: String(index + 4),
      provisionalId: `catalog-live-progress-${index + 1}`,
      replayable: true,
      kind: "assistant_message" as const,
      assistantKind: "progress" as const,
      text: `Progress checkpoint ${index + 1}: validating one bounded repository invariant.`,
    })),
    {
      workspaceId: workspace.id,
      sessionId: session.id,
      runId: "catalog-run-active",
      sequence: 10,
      runSequence: "10",
      provisionalId: "catalog-live-approval",
      replayable: true,
      kind: "approval_requested",
      itemId: "catalog-approval-call",
      toolName: "bash",
      approval: {
        callId: "catalog-approval-call",
        toolName: "bash",
        approvalRequestId: "catalog-approval-request",
        toolCallHash: "catalog-approval-tool-hash",
        policyVersion: "catalog-policy-v1",
        expiresAtMs: 4_102_444_800_000,
        operation: "execute_read_only_command",
        risk: "low",
        snapshotRequired: false,
        previewTitle: "External directory access for bash",
        previewSummary: "This tool call touches a path outside the workspace.",
        previewBody: "cd /workspace && cargo test -p sigil-runtime",
      },
    },
  ],
  streamState: "live",
  hasGap: false,
};

const runContext: RunContext = {
  providerName: "deepseek",
  modelName: "deepseek-v4-flash",
  availableModels: ["deepseek-v4-flash", "deepseek-v4-pro"],
  modelOptions: [
    {
      modelName: "deepseek-v4-flash",
      availableReasoningEfforts: ["low", "medium", "high", "max"],
      defaultReasoningEffort: "max",
      reasoningEffortBinding: "catalog-effort-binding",
    },
    {
      modelName: "deepseek-v4-pro",
      availableReasoningEfforts: ["low", "medium", "high", "max"],
      defaultReasoningEffort: "max",
      reasoningEffortBinding: "catalog-effort-binding-pro",
    },
  ],
  modelSelection: "per_run",
  modelSelectionBinding: "catalog-model-binding",
  defaultPermissionMode: "manual",
  availablePermissionModes: ["read-only", "manual", "auto-edit", "danger-full-access"],
  availableReasoningEfforts: ["low", "medium", "high", "max"],
  defaultReasoningEffort: "max",
  reasoningEffortBinding: "catalog-effort-binding",
  contextWindowTokens: 1_000_000,
  lastPromptTokens: 42_000,
  contextWindowSource: "provider",
  extensionCatalog: { commands: [], skills: [], agents: [] },
};

const verification: VerificationSummary = {
  taskId: "catalog-task",
  stepId: "catalog-verify",
  scopeKind: "step",
  scopeId: "catalog-task:catalog-verify",
  verdict: "failed",
  status: "check failed",
  recommendedCheckSpecId: "cargo-test-parser",
  recommendationKind: "retry",
  recommendationReason: "The exact parser check failed for the current workspace snapshot.",
  action: {
    kind: "rerun",
    request: {
      taskId: "catalog-task",
      stepId: "catalog-verify",
      checkSpecId: "cargo-test-parser",
      checkSpecHash: "catalog-check-spec-hash",
      policyHash: "catalog-policy-hash",
      workspaceSnapshotId: "catalog-snapshot",
    },
  },
  evidence: {
    receiptId: "catalog-receipt",
    workspaceSnapshotId: "catalog-snapshot",
    changesetId: "catalog-changeset",
    commandEventId: "catalog-command",
    outputArtifactId: "catalog-output",
    failureSummary: "tests/parser.rs:42: expected diagnostic context",
  },
};

function appearance(preference: ThemePreference): AppearanceSnapshot {
  const resolvedTheme = preference === "system"
    ? resolveSystemTheme()
    : preference;
  return { preference, resolvedTheme };
}

export function createCatalogWorkbenchBridge(
  preference: ThemePreference,
): DesktopBridge {
  let currentPreference = preference;
  return {
    bootstrap: async () => ({
      protocolVersion: 2,
      workspaces: [workspace],
      recentWorkspaces: [],
      appearance: appearance(currentPreference),
    }),
    setAppearance: async (next) => {
      currentPreference = next;
      return appearance(currentPreference);
    },
    openExternalUrl: async () => undefined,
    supportDoctor: async () => ({
      generatedAtUnixMs: 1_784_419_200_000,
      version: "catalog",
      commit: "catalog",
      target: "aarch64-apple-darwin",
      profile: "debug",
      environment: { os: "macos", architecture: "aarch64", terminalFamily: "other" },
      summary: { overallStatus: "ok", ok: 5, warn: 0, error: 0 },
      checks: [],
      privacy: { included: ["build metadata"], excluded: ["credentials"], reviewBeforeSharing: true },
    }),
    exportSupportBundle: async () => ({ cancelled: false, fileName: "sigil-support-catalog.json" }),
    pickWorkspace: async () => ({ cancelled: true }),
    openRecentWorkspace: async () => workspace,
    closeWorkspace: async () => [],
    catalog: async () => catalog,
    createSession: async () => session,
    openSession: async () => session,
    renameSession: async (_workspaceId, input) => ({
      sessionRef: input.sessionRef,
      sessionId: input.sessionId,
      projectionGeneration: 2,
    }),
    deleteSession: async (_workspaceId, input) => ({
      sessionRef: input.sessionRef,
      sessionId: input.sessionId,
      projectionGeneration: 2,
    }),
    quarantineSession: async (_workspaceId, input) => ({
      sessionRef: input.sessionRef,
      quarantineName: `quarantined--${input.sessionRef}`,
      projectionGeneration: 2,
    }),
    deleteInvalidSessionSource: async (_workspaceId, input) => ({
      sessionRef: input.sessionRef,
      projectionGeneration: 2,
    }),
    planSessionCatalogBatch: async (_workspaceId, input) => ({
      planId: "sha256:catalog-plan",
      action: input.action,
      generation: catalog.generation,
      total: input.items.length,
      executable: input.items.length,
      blocked: 0,
      items: input.items.map((item) => ({ sessionRef: item.sessionRef, status: "executable" })),
    }),
    executeSessionCatalogBatch: async (_workspaceId, input) => ({
      planId: input.planId,
      action: input.action,
      total: input.items.length,
      completed: input.items.length,
      failed: 0,
      skipped: 0,
      items: input.items.map((item) => ({ sessionRef: item.sessionRef, outcome: "completed" })),
    }),
    transcript: async () => transcript,
    display: async () => displayPage,
    continuity: async () => ({
      durableFrontier: { throughStreamSequence: 3 },
      foregroundOwner: {
        runId: attachment.run.id,
        ownerRevision: `sha256:${"c".repeat(64)}`,
      },
      recoveryActions: ["retry_current", "continue_read_only"],
    }),
    conversationQueue: async (_workspaceId, sessionId) => ({
      schemaVersion: 1,
      sessionId,
      generation: "0",
      paused: false,
      totalItems: 0,
      items: [],
      truncated: false,
    }),
    commandConversationQueue: async (_workspaceId, input) => ({
      commandId: "catalog-queue-command",
      clientId: "sigil-desktop-catalog",
      sessionId: input.sessionId,
      action: input.action.action,
      expectedGeneration: input.expectedGeneration,
      generation: input.expectedGeneration,
      queue: {
        schemaVersion: 1,
        sessionId: input.sessionId,
        generation: input.expectedGeneration,
        paused: input.action.action === "pause",
        totalItems: 0,
        items: [],
        truncated: false,
      },
      replayed: false,
    }),
    conversationRecovery: async () => ({ checkpoints: [], forkPoints: [], throughStreamSequence: 0 }),
    conversationCompactionPreview: async () => ({
      foldedEventCount: 0,
      retainedEventCount: 0,
      admission: { kind: "no_foldable_history", durableMessageCount: 0, configuredTailMessageCount: 12 },
    }),
    checkpointRestorePreview: async (_workspaceId, input) => ({
      checkpointId: input.checkpointId,
      checkpointDigest: input.checkpointDigest,
      files: [],
      reverseDiffs: [],
      unknownMutationCount: 0,
      ready: true,
    }),
    commandConversationRecovery: async (_workspaceId, input) => ({
      commandId: "catalog-recovery-command",
      clientId: "sigil-desktop-catalog",
      sessionId: input.sessionId,
      action: input.action.kind,
      recovery: { checkpoints: [], forkPoints: [], throughStreamSequence: 0 },
      replayed: false,
    }),
    runContext: async () => runContext,
    agentActivity: async () => ({
      totalAgents: 0,
      activeAgents: 0,
      terminalAgents: 0,
      items: [],
    }),
    startRun: async (
      _workspaceId,
      sessionId,
      _prompt,
      permissionMode,
      _modelName,
      _modelSelectionBinding,
      reasoningEffort,
    ) => ({
      id: "catalog-run-new",
      sessionId,
      status: "running",
      permissionMode,
      reasoningEffort,
      streamSequence: 0,
    }),
    attachRun: async () => attachment,
    cancelRun: async (_workspaceId, sessionId, runId) => ({
      id: runId,
      sessionId,
      status: "cancel_requested",
      permissionMode: "manual",
      streamSequence: 4,
    }),
    resolveApproval: async (_workspaceId, _sessionId, runId, request, approve) => ({
      runId,
      callId: request.callId,
      decision: approve ? "approved" : "denied",
    }),
    verification: async () => verification,
    rerunVerification: async () => ({ ...verification, verdict: "passed", status: "passed" }),
    subscribeRunEvents: async () => () => undefined,
    subscribeRunStreamStatus: async () => () => undefined,
    subscribeAppearance: async () => () => undefined,
  };
}
