use anyhow::{Result, bail};
use ratatui::style::Color;
use sigil_kernel::ThemeColorOverrides;

use super::palette::ThemePalette;

#[allow(dead_code)]
pub(crate) const COLOR_TOKEN_NAMES: &[&str] = &[
    "surface_base",
    "surface_rail",
    "surface_panel",
    "surface_panel_alt",
    "surface_input",
    "surface_agent_panel",
    "surface_overlay",
    "surface_overlay_shadow",
    "surface_badge",
    "surface_selection",
    "surface_user_message",
    "surface_code",
    "border_subtle",
    "border_strong",
    "border_focus",
    "border_danger",
    "text_primary",
    "text_secondary",
    "text_muted",
    "text_inverse",
    "text_disabled",
    "accent_primary",
    "accent_secondary",
    "accent_info",
    "accent_success",
    "accent_warning",
    "accent_danger",
    "accent_streaming",
    "accent_idle",
    "selection_fg",
    "selection_bg",
    "button_selected_fg",
    "button_selected_bg",
    "button_inactive_fg",
    "diff_header_fg",
    "diff_hunk_fg",
    "diff_added_fg",
    "diff_added_bg",
    "diff_removed_fg",
    "diff_removed_bg",
    "diff_context_fg",
    "diff_gutter_fg",
    "diff_current_hunk_bg",
    "approval_bg",
    "approval_backdrop_bg",
    "approval_border",
    "approval_shadow",
    "risk_low",
    "risk_medium",
    "risk_high",
    "approval_allow_bg",
    "approval_deny_bg",
    "approval_selected_bg",
    "markdown_heading",
    "markdown_quote_bar",
    "markdown_quote_text",
    "markdown_rule",
    "markdown_code_fg",
    "markdown_code_bg",
    "markdown_link",
    "modal_bg",
    "modal_border",
    "modal_shadow",
    "modal_command_bg",
    "modal_selected_bg",
    "overlay_bg",
    "overlay_shadow",
    "config_bg",
    "config_border",
    "config_primary",
    "config_detail",
    "config_warning",
    "config_danger",
    "config_tab_bg",
    "config_section_bg",
    "config_selected_bg",
    "setup_bg",
    "status_idle",
    "status_thinking",
    "status_tool",
    "status_streaming",
    "status_success",
    "status_warning",
    "status_error",
    "status_pending",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ColorTokenGroup {
    pub(crate) key: &'static str,
    pub(crate) label: &'static str,
    pub(crate) tokens: &'static [&'static str],
}

pub(crate) const COLOR_TOKEN_GROUPS: &[ColorTokenGroup] = &[
    ColorTokenGroup {
        key: "surfaces",
        label: "Surfaces",
        tokens: &[
            "surface_base",
            "surface_rail",
            "surface_panel",
            "surface_panel_alt",
            "surface_input",
            "surface_agent_panel",
            "surface_overlay",
            "surface_overlay_shadow",
            "surface_badge",
            "surface_selection",
            "surface_user_message",
            "surface_code",
        ],
    },
    ColorTokenGroup {
        key: "borders",
        label: "Borders",
        tokens: &[
            "border_subtle",
            "border_strong",
            "border_focus",
            "border_danger",
        ],
    },
    ColorTokenGroup {
        key: "text",
        label: "Text",
        tokens: &[
            "text_primary",
            "text_secondary",
            "text_muted",
            "text_inverse",
            "text_disabled",
        ],
    },
    ColorTokenGroup {
        key: "accents",
        label: "Accents",
        tokens: &[
            "accent_primary",
            "accent_secondary",
            "accent_info",
            "accent_success",
            "accent_warning",
            "accent_danger",
            "accent_streaming",
            "accent_idle",
        ],
    },
    ColorTokenGroup {
        key: "selection_buttons",
        label: "Selection/buttons",
        tokens: &[
            "selection_fg",
            "selection_bg",
            "button_selected_fg",
            "button_selected_bg",
            "button_inactive_fg",
        ],
    },
    ColorTokenGroup {
        key: "status",
        label: "Status",
        tokens: &[
            "status_idle",
            "status_thinking",
            "status_tool",
            "status_streaming",
            "status_success",
            "status_warning",
            "status_error",
            "status_pending",
        ],
    },
    ColorTokenGroup {
        key: "diff",
        label: "Diff",
        tokens: &[
            "diff_header_fg",
            "diff_hunk_fg",
            "diff_added_fg",
            "diff_added_bg",
            "diff_removed_fg",
            "diff_removed_bg",
            "diff_context_fg",
            "diff_gutter_fg",
            "diff_current_hunk_bg",
        ],
    },
    ColorTokenGroup {
        key: "approval",
        label: "Approval",
        tokens: &[
            "approval_bg",
            "approval_backdrop_bg",
            "approval_border",
            "approval_shadow",
            "risk_low",
            "risk_medium",
            "risk_high",
            "approval_allow_bg",
            "approval_deny_bg",
            "approval_selected_bg",
        ],
    },
    ColorTokenGroup {
        key: "markdown",
        label: "Markdown",
        tokens: &[
            "markdown_heading",
            "markdown_quote_bar",
            "markdown_quote_text",
            "markdown_rule",
            "markdown_code_fg",
            "markdown_code_bg",
            "markdown_link",
        ],
    },
    ColorTokenGroup {
        key: "modal_overlay",
        label: "Modal/overlay",
        tokens: &[
            "modal_bg",
            "modal_border",
            "modal_shadow",
            "modal_command_bg",
            "modal_selected_bg",
            "overlay_bg",
            "overlay_shadow",
        ],
    },
    ColorTokenGroup {
        key: "config",
        label: "Config",
        tokens: &[
            "config_bg",
            "config_border",
            "config_primary",
            "config_detail",
            "config_warning",
            "config_danger",
            "config_tab_bg",
            "config_section_bg",
            "config_selected_bg",
            "setup_bg",
        ],
    },
];

pub(crate) fn apply_overrides(
    palette: &mut ThemePalette,
    overrides: &ThemeColorOverrides,
) -> Result<()> {
    for (token, value) in overrides.iter() {
        let color = parse_hex_color(token, value)?;
        apply_token(palette, token, color)?;
    }
    Ok(())
}

pub(crate) fn parse_hex_color(token: &str, value: &str) -> Result<Color> {
    let value = value.trim();
    if value.len() != 7 || !value.starts_with('#') {
        bail!("appearance.colors.{token} must be #RRGGBB");
    }
    let parse = |range: std::ops::Range<usize>| -> Result<u8> {
        u8::from_str_radix(&value[range], 16)
            .map_err(|_| anyhow::anyhow!("appearance.colors.{token} must be #RRGGBB"))
    };
    Ok(Color::Rgb(parse(1..3)?, parse(3..5)?, parse(5..7)?))
}

fn apply_token(palette: &mut ThemePalette, token: &str, color: Color) -> Result<()> {
    match token {
        "surface_base" => palette.surface_base = color,
        "surface_rail" => palette.surface_rail = color,
        "surface_panel" => palette.surface_panel = color,
        "surface_panel_alt" => palette.surface_panel_alt = color,
        "surface_input" => palette.surface_input = color,
        "surface_agent_panel" => palette.surface_agent_panel = color,
        "surface_overlay" => palette.surface_overlay = color,
        "surface_overlay_shadow" => palette.surface_overlay_shadow = color,
        "surface_badge" => palette.surface_badge = color,
        "surface_selection" => palette.surface_selection = color,
        "surface_user_message" => palette.surface_user_message = color,
        "surface_code" => palette.surface_code = color,
        "border_subtle" => palette.border_subtle = color,
        "border_strong" => palette.border_strong = color,
        "border_focus" => palette.border_focus = color,
        "border_danger" => palette.border_danger = color,
        "text_primary" => palette.text_primary = color,
        "text_secondary" => palette.text_secondary = color,
        "text_muted" => palette.text_muted = color,
        "text_inverse" => palette.text_inverse = color,
        "text_disabled" => palette.text_disabled = color,
        "accent_primary" => palette.accent_primary = color,
        "accent_secondary" => palette.accent_secondary = color,
        "accent_info" => palette.accent_info = color,
        "accent_success" => palette.accent_success = color,
        "accent_warning" => palette.accent_warning = color,
        "accent_danger" => palette.accent_danger = color,
        "accent_streaming" => palette.accent_streaming = color,
        "accent_idle" => palette.accent_idle = color,
        "selection_fg" => palette.selection_fg = color,
        "selection_bg" => palette.selection_bg = color,
        "button_selected_fg" => palette.button_selected_fg = color,
        "button_selected_bg" => palette.button_selected_bg = color,
        "button_inactive_fg" => palette.button_inactive_fg = color,
        "diff_header_fg" => palette.diff_header_fg = color,
        "diff_hunk_fg" => palette.diff_hunk_fg = color,
        "diff_added_fg" => palette.diff_added_fg = color,
        "diff_added_bg" => palette.diff_added_bg = color,
        "diff_removed_fg" => palette.diff_removed_fg = color,
        "diff_removed_bg" => palette.diff_removed_bg = color,
        "diff_context_fg" => palette.diff_context_fg = color,
        "diff_gutter_fg" => palette.diff_gutter_fg = color,
        "diff_current_hunk_bg" => palette.diff_current_hunk_bg = color,
        "approval_bg" => palette.approval_bg = color,
        "approval_backdrop_bg" => palette.approval_backdrop_bg = color,
        "approval_border" => palette.approval_border = color,
        "approval_shadow" => palette.approval_shadow = color,
        "risk_low" => palette.risk_low = color,
        "risk_medium" => palette.risk_medium = color,
        "risk_high" => palette.risk_high = color,
        "approval_allow_bg" => palette.approval_allow_bg = color,
        "approval_deny_bg" => palette.approval_deny_bg = color,
        "approval_selected_bg" => palette.approval_selected_bg = color,
        "markdown_heading" => palette.markdown_heading = color,
        "markdown_quote_bar" => palette.markdown_quote_bar = color,
        "markdown_quote_text" => palette.markdown_quote_text = color,
        "markdown_rule" => palette.markdown_rule = color,
        "markdown_code_fg" => palette.markdown_code_fg = color,
        "markdown_code_bg" => palette.markdown_code_bg = color,
        "markdown_link" => palette.markdown_link = color,
        "modal_bg" => palette.modal_bg = color,
        "modal_border" => palette.modal_border = color,
        "modal_shadow" => palette.modal_shadow = color,
        "modal_command_bg" => palette.modal_command_bg = color,
        "modal_selected_bg" => palette.modal_selected_bg = color,
        "overlay_bg" => palette.overlay_bg = color,
        "overlay_shadow" => palette.overlay_shadow = color,
        "config_bg" => palette.config_bg = color,
        "config_border" => palette.config_border = color,
        "config_primary" => palette.config_primary = color,
        "config_detail" => palette.config_detail = color,
        "config_warning" => palette.config_warning = color,
        "config_danger" => palette.config_danger = color,
        "config_tab_bg" => palette.config_tab_bg = color,
        "config_section_bg" => palette.config_section_bg = color,
        "config_selected_bg" => palette.config_selected_bg = color,
        "setup_bg" => palette.setup_bg = color,
        "status_idle" => palette.status_idle = color,
        "status_thinking" => palette.status_thinking = color,
        "status_tool" => palette.status_tool = color,
        "status_streaming" => palette.status_streaming = color,
        "status_success" => palette.status_success = color,
        "status_warning" => palette.status_warning = color,
        "status_error" => palette.status_error = color,
        "status_pending" => palette.status_pending = color,
        _ => bail!("unknown appearance.colors token {token}"),
    }
    Ok(())
}
