use ratatui::style::Color;

use crate::app::RunPhase;

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ThemePalette {
    pub(crate) surface_base: Color,
    pub(crate) surface_rail: Color,
    pub(crate) surface_panel: Color,
    pub(crate) surface_panel_alt: Color,
    pub(crate) surface_input: Color,
    pub(crate) surface_agent_panel: Color,
    pub(crate) surface_overlay: Color,
    pub(crate) surface_overlay_shadow: Color,
    pub(crate) surface_badge: Color,
    pub(crate) surface_selection: Color,
    pub(crate) surface_user_message: Color,
    pub(crate) surface_code: Color,
    pub(crate) border_subtle: Color,
    pub(crate) border_strong: Color,
    pub(crate) border_focus: Color,
    pub(crate) border_danger: Color,
    pub(crate) text_primary: Color,
    pub(crate) text_secondary: Color,
    pub(crate) text_muted: Color,
    pub(crate) text_inverse: Color,
    pub(crate) text_disabled: Color,
    pub(crate) accent_primary: Color,
    pub(crate) accent_secondary: Color,
    pub(crate) accent_info: Color,
    pub(crate) accent_success: Color,
    pub(crate) accent_warning: Color,
    pub(crate) accent_danger: Color,
    pub(crate) accent_streaming: Color,
    pub(crate) accent_idle: Color,
    pub(crate) selection_fg: Color,
    pub(crate) selection_bg: Color,
    pub(crate) button_selected_fg: Color,
    pub(crate) button_selected_bg: Color,
    pub(crate) button_inactive_fg: Color,
    pub(crate) diff_header_fg: Color,
    pub(crate) diff_hunk_fg: Color,
    pub(crate) diff_added_fg: Color,
    pub(crate) diff_added_bg: Color,
    pub(crate) diff_removed_fg: Color,
    pub(crate) diff_removed_bg: Color,
    pub(crate) diff_context_fg: Color,
    pub(crate) diff_gutter_fg: Color,
    pub(crate) diff_current_hunk_bg: Color,
    pub(crate) approval_bg: Color,
    pub(crate) approval_backdrop_bg: Color,
    pub(crate) approval_border: Color,
    pub(crate) approval_shadow: Color,
    pub(crate) risk_low: Color,
    pub(crate) risk_medium: Color,
    pub(crate) risk_high: Color,
    pub(crate) approval_allow_bg: Color,
    pub(crate) approval_deny_bg: Color,
    pub(crate) approval_selected_bg: Color,
    pub(crate) markdown_heading: Color,
    pub(crate) markdown_quote_bar: Color,
    pub(crate) markdown_quote_text: Color,
    pub(crate) markdown_rule: Color,
    pub(crate) markdown_code_fg: Color,
    pub(crate) markdown_code_bg: Color,
    pub(crate) markdown_link: Color,
    pub(crate) modal_bg: Color,
    pub(crate) modal_border: Color,
    pub(crate) modal_shadow: Color,
    pub(crate) modal_command_bg: Color,
    pub(crate) modal_selected_bg: Color,
    pub(crate) overlay_bg: Color,
    pub(crate) overlay_shadow: Color,
    pub(crate) config_bg: Color,
    pub(crate) config_border: Color,
    pub(crate) config_primary: Color,
    pub(crate) config_detail: Color,
    pub(crate) config_warning: Color,
    pub(crate) config_danger: Color,
    pub(crate) config_tab_bg: Color,
    pub(crate) config_section_bg: Color,
    pub(crate) config_selected_bg: Color,
    pub(crate) setup_bg: Color,
    pub(crate) status_idle: Color,
    pub(crate) status_thinking: Color,
    pub(crate) status_tool: Color,
    pub(crate) status_streaming: Color,
    pub(crate) status_success: Color,
    pub(crate) status_warning: Color,
    pub(crate) status_error: Color,
    pub(crate) status_pending: Color,
}

impl ThemePalette {
    pub(crate) fn phase_accent(&self, phase: &RunPhase) -> Color {
        match phase {
            RunPhase::Idle => self.status_idle,
            RunPhase::Thinking => self.status_thinking,
            RunPhase::Agent(_) => self.accent_info,
            RunPhase::Tool(_) => self.status_tool,
            RunPhase::Streaming => self.status_streaming,
        }
    }
}
