[package]
name = "sigil-process-observer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sigil-kernel = { path = "../sigil-kernel" }
sigil-process = { path = "../sigil-process" }
ring.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
